SELECT * FROM ALL_TABLES;
DROP TABLE MEMBER; 
DROP TABLE FREEBOARD;
DROP TABLE STUDYBOARD;
DROP TABLE NOTICEBOARD;
DROP TABLE CONCERM;
DROP TABLE FREECOMMENT;
DROP TABLE STUDYCOMMENT;
DROP TABLE NOTICECOMMENT;

SELECT * FROM FREEBOARD WHERE PTITLE LIKE '%페이%' ORDER BY PNUM DESC;
SELECT COUNT(*) FROM FREEBOARD;

SELECT * FROM (SELECT ROWNUM AS PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT,CATEGORY FROM FREEBOARD ORDER BY PNUM) WHERE PNUM BETWEEN 1 AND 5;

-- 유저 테이블
CREATE TABLE MEMBER(
	MID VARCHAR(50) PRIMARY KEY,				-- 회원 아이디
	MPW VARCHAR(50) NOT NULL,					-- 회원 비밀번호
	MNAME VARCHAR(50) NOT NULL,					-- 회원 닉네임
	MEMAIL VARCHAR(50) NOT NULL,				-- 회원 이메일
	ROLE VARCHAR(20) DEFAULT 'user' NOT NULL 	-- 사용자/관리자
);
INSERT INTO MEMBER VALUES ('hana','11','하나','hana11@naver.com','user');
INSERT INTO MEMBER VALUES ('qwe','qwe','qwe','hana11@naver.com','user');
INSERT INTO MEMBER VALUES ('asd','asd','일','a@naver.com','user');
INSERT INTO MEMBER VALUES ('zxc','zxc','삼','b@naver.com','user');
INSERT INTO MEMBER VALUES ('admin','1004','관리자','admin@helper.com','admin');
update member set mpw='asd' where mid='asd';

SELECT * FROM MEMBER;
SELECT * FROM MEMBER where mid='qwe';
-- ====================================================================
-- 게시글 테이블 
CREATE TABLE FREEBOARD(			 		 			 -- 자유게시판
	PNUM INT PRIMARY KEY, 				 	   		 -- 게시글 고유 번호
	PTITLE VARCHAR(50) NOT NULL,		 			 -- 게시글 제목 
	PCONTENT VARCHAR(1000) NOT NULL,				 -- 게시글 내용
	PDATE DATE DEFAULT SYSDATE NOT NULL,			 -- 게시글 작성일자 
	MNAME VARCHAR(50) NOT NULL,						 -- 회원 닉네임
	MID VARCHAR(50) NOT NULL,						 -- 회원 아이디
	CNT INT DEFAULT 0 NOT NULL, 					 -- 조회수
	CATEGORY VARCHAR(50) DEFAULT 'Free' NOT NULL 	 -- 카테고리 
);
-- 게시글 리스트 보기
SELECT * FROM FREEBOARD ORDER BY PNUM DESC; --최신글 
SELECT * FROM FREEBOARD WHERE PTITLE= LIKE '%H%' ORDER BY PNUM DESC;  --수정
-- 게시글 상세 보기
SELECT * FROM FREEBOARD WHERE PNUM = 1 ;
-- 테이블 전체 행 개수 가져오기 
SELECT COUNT(*) FROM FREEBOARD;

-- 게시글 작성
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'Test.01','TestMessage.01',SYSDATE,'hana','하나',0);


-- 수정
UPDATE FREEBOARD SET PTITLE='HI',PCONTENT='★★★★★★★★★' WHERE PNUM=1;

-- 삭제
DELETE FROM FREEBOARD WHERE PNUM ='2' AND MID='duri';
DELETE FROM MEMBER WHERE ROWNUM >='1' AND ROWNUM <='30' ;
CREATE TABLE STUDYBOARD(							-- 스터디게시판
	PNUM INT PRIMARY KEY, 				 			-- 게시글 고유 번호
	PTITLE VARCHAR(50) NOT NULL,		 			-- 게시글 제목
	PCONTENT VARCHAR(1000) NOT NULL,	 			-- 게시글 내용
	PDATE DATE DEFAULT SYSDATE NOT NULL, 			-- 게시글 작성일자
	MNAME VARCHAR(50) NOT NULL,			 			-- 회원 닉네임
	MID VARCHAR(50) NOT NULL,			 			-- 회원 아이디
	CNT INT DEFAULT 0 NOT NULL, 					-- 조회수
	CATEGORY VARCHAR(50) DEFAULT 'Study' NOT NULL 	-- 카테고리
);
CREATE TABLE NOTICEBOARD(							-- 공지게시판
	PNUM INT PRIMARY KEY, 						 	-- 게시글 고유 번호
	PTITLE VARCHAR(50) NOT NULL,		 		 	-- 게시글 제목 
	PCONTENT VARCHAR(1000) NOT NULL,			 	-- 게시글 내용
	PDATE DATE DEFAULT SYSDATE NOT NULL, 		 	-- 게시글 작성일자 
	MNAME VARCHAR(50) NOT NULL,			 	   	 	-- 회원 닉네임
	MID VARCHAR(50) NOT NULL,					 	-- 회원 아이디
	CNT INT DEFAULT 0 NOT NULL, 				 	-- 조회수
	CATEGORY VARCHAR(50) DEFAULT 'Notice' NOT NULL 	-- 카테고리 
);



-- ====================================================================
-- 관심글 게시글 테이블 
CREATE TABLE CONCERM(
	FAVNUM INT PRIMARY KEY,				 -- 관심 게시글 고유 번호  
	MID VARCHAR(50) NOT NULL,			 -- 회원 아이디
	MNAME VARCHAR(50) NOT NULL,			 -- 회원 아이디
	PNUM INT NOT NULL, 					 -- 게시글 번호
	PTITLE VARCHAR(50) NOT NULL,		 -- 게시글 제목
	CATEGORY VARCHAR(50) NOT NULL		 -- 카테고리
);
-- 관심글 목록 보기
SELECT * FROM CONCERM ORDER BY FAVNUM DESC;
-- 관심글 등록 
INSERT INTO CONCERM VALUES ((SELECT NVL(MAX(FAVNUM),0)+1 FROM CONCERM),'hana','1','Test.01','자유게시판');
INSERT INTO CONCERM VALUES ((SELECT NVL(MAX(FAVNUM),0)+1 FROM CONCERM),'hana','2','Test.02','자유게시판');

-- 관심글 삭제 
DELETE FROM CONCERM WHERE FAVNUM =5 AND MID='qwe';

-- ====================================================================
-- 댓글테이블 
CREATE TABLE FREECOMMENT(				 -- 자유게시판 댓글
	CNUM INT PRIMARY KEY,				 -- 댓글 고유 번호 
	COMM VARCHAR(200) NOT NULL,		 -- 댓글 내용 
	CDATE DATE DEFAULT SYSDATE NOT NULL, -- 댓글 작성 일자
	PNUM INT NOT NULL,					 -- 게시글 번호  
	MNAME VARCHAR(50) NOT NULL, 		 -- 회원 닉네임
	MID VARCHAR(50) NOT NULL,			 -- 회원 아이디 
	
	CONSTRAINT fcodel FOREIGN KEY (PNUM) REFERENCES FREEBOARD(PNUM) ON DELETE CASCADE

);

CREATE TABLE STUDYCOMMENT(				 -- 스터디게시판 댓글
	CNUM INT PRIMARY KEY,				 -- 댓글 고유 번호 
	COMM VARCHAR(200) NOT NULL,		 -- 댓글 내용 
	CDATE DATE DEFAULT SYSDATE NOT NULL, -- 댓글 작성 일자
	PNUM INT NOT NULL,					 -- 게시글 번호  
	MNAME VARCHAR(50) NOT NULL, 		 -- 회원 닉네임
	MID VARCHAR(50) NOT NULL,			 -- 회원 아이디 
	CONSTRAINT scodel FOREIGN KEY (PNUM) REFERENCES STUDYBOARD(PNUM) ON DELETE CASCADE
);

CREATE TABLE NOTICECOMMENT(				 -- 공지게시판 댓글
	CNUM INT PRIMARY KEY,				 -- 댓글 고유 번호 
	COMM VARCHAR(200) NOT NULL,		 -- 댓글 내용 
	CDATE DATE DEFAULT SYSDATE NOT NULL, -- 댓글 작성 일자
	PNUM INT NOT NULL,				 	 -- 게시글 번호  
	MNAME VARCHAR(50) NOT NULL, 		 -- 회원 닉네임
	MID VARCHAR(50) NOT NULL,			 -- 회원 아이디 
	CONSTRAINT ncodel FOREIGN KEY (PNUM) REFERENCES NOTICEBOARD(PNUM) ON DELETE CASCADE
);


-- ================================================================================
-- 임시 데이터 
-- MEMBER
INSERT INTO MEMBER VALUES ('hana','11','하나','hana11@naver.com','user');
INSERT INTO MEMBER VALUES ('an','11','테스트','ananan@naver.com','user');
INSERT INTO MEMBER VALUES ('admin','1004','관리자','admin@helper.com','admin');

-- FREEBOARD
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'FreeTest.01','TestMessage.01',SYSDATE,'테스트','an',0);
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'FreeTest.02','TestMessage.01',SYSDATE,'하나','hana',0);
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'FreeTest.03','TestMessage.01',SYSDATE,'하나','hana',0);
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'FreeTest.04','TestMessage.01',SYSDATE,'테스트','an',0);
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'FreeTest.05','TestMessage.01',SYSDATE,'테스트','an',0);
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'FreeTest.06','TestMessage.01',SYSDATE,'테스트','an',0);
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'FreeTest.07','TestMessage.01',SYSDATE,'하나','hana',0);
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'FreeTest.08','TestMessage.01',SYSDATE,'하나','hana',0);
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'FreeTest.09','TestMessage.01',SYSDATE,'하나','hana',0);
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'FreeTest.10','TestMessage.01',SYSDATE,'하나','hana',0);
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'FreeTest.11','TestMessage.01',SYSDATE,'하나','hana',0);
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'FreeTest.12','TestMessage.01',SYSDATE,'하나','hana',0);
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'FreeTest.13','TestMessage.01',SYSDATE,'하나','hana',0);
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'FreeTest.14','TestMessage.01',SYSDATE,'하나','hana',0);
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'FreeTest.15','TestMessage.01',SYSDATE,'하나','hana',0);
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'FreeTest.16','TestMessage.01',SYSDATE,'하나','hana',0);
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'FreeTest.17','TestMessage.01',SYSDATE,'하나','hana',0);
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'FreeTest.18','TestMessage.01',SYSDATE,'하나','hana',0);
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'FreeTest.19','TestMessage.01',SYSDATE,'하나','hana',0);
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'FreeTest.20','TestMessage.01',SYSDATE,'테스트','an',0);
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'FreeTest.21','TestMessage.01',SYSDATE,'테스트','an',0);
INSERT INTO FREEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM FREEBOARD),
'FreeTest.22','TestMessage.01',SYSDATE,'테스트','an',0);


-- STUDYBOARD
INSERT INTO STUDYBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM STUDYBOARD),
'STUDY TEST.01','STUDY18',SYSDATE,'하나','hana',0);
INSERT INTO STUDYBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM STUDYBOARD),
'STUDY TEST.02','STUDY18',SYSDATE,'테스트','an',0);
INSERT INTO STUDYBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM STUDYBOARD),
'STUDY TEST.03','STUDY18',SYSDATE,'테스트','an',0);
INSERT INTO STUDYBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM STUDYBOARD),
'STUDY TEST.04','STUDY18',SYSDATE,'테스트','an',0);
INSERT INTO STUDYBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM STUDYBOARD),
'STUDY TEST.05','STUDY18',SYSDATE,'하나','hana',0);
INSERT INTO STUDYBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM STUDYBOARD),
'STUDY TEST.06','STUDY18',SYSDATE,'하나','hana',0);
INSERT INTO STUDYBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM STUDYBOARD),
'STUDY TEST.07','STUDY18',SYSDATE,'하나','hana',0);
INSERT INTO STUDYBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM STUDYBOARD),
'STUDY TEST.08','STUDY18',SYSDATE,'하나','hana',0);
INSERT INTO STUDYBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM STUDYBOARD),
'STUDY TEST.09','STUDY18',SYSDATE,'하나','hana',0);
INSERT INTO STUDYBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM STUDYBOARD),
'STUDY TEST.10','STUDY18',SYSDATE,'하나','hana',0);
INSERT INTO STUDYBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM STUDYBOARD),
'STUDY TEST.11','STUDY18',SYSDATE,'하나','hana',0);
INSERT INTO STUDYBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM STUDYBOARD),
'STUDY TEST.12','STUDY18',SYSDATE,'하나','hana',0);
INSERT INTO STUDYBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM STUDYBOARD),
'STUDY TEST.13','STUDY18',SYSDATE,'하나','hana',0);
INSERT INTO STUDYBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM STUDYBOARD),
'STUDY TEST.14','STUDY18',SYSDATE,'하나','hana',0);
INSERT INTO STUDYBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM STUDYBOARD),
'STUDY TEST.15','STUDY18',SYSDATE,'하나','hana',0);
INSERT INTO STUDYBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM STUDYBOARD),
'STUDY TEST.16','STUDY18',SYSDATE,'하나','hana',0);
INSERT INTO STUDYBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM STUDYBOARD),
'STUDY TEST.17','STUDY18',SYSDATE,'테스트','an',0);
INSERT INTO STUDYBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM STUDYBOARD),
'STUDY TEST.18','STUDY18',SYSDATE,'테스트','an',0);
INSERT INTO STUDYBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM STUDYBOARD),
'STUDY TEST.19','STUDY18',SYSDATE,'테스트','an',0);

-- NOTICEBOARD
INSERT INTO NOTICEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM NOTICEBOARD),
'NOTICE 1','NOTICE 1',SYSDATE,'테스트','an',0);
INSERT INTO NOTICEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM NOTICEBOARD),
'NOTICE 2','NOTICE 2',SYSDATE,'하나','hana',0);
INSERT INTO NOTICEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM NOTICEBOARD),
'NOTICE 3','NOTICE 3',SYSDATE,'테스트','an',0);
INSERT INTO NOTICEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM NOTICEBOARD),
'NOTICE 4','NOTICE 4',SYSDATE,'하나','hana',0);
INSERT INTO NOTICEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM NOTICEBOARD),
'NOTICE 5','NOTICE 5',SYSDATE,'하나','hana',0);
INSERT INTO NOTICEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM NOTICEBOARD),
'NOTICE 6','NOTICE 6',SYSDATE,'하나','hana',0);
INSERT INTO NOTICEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM NOTICEBOARD),
'NOTICE 7','NOTICE 7',SYSDATE,'하나','hana',0);
INSERT INTO NOTICEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM NOTICEBOARD),
'NOTICE 8','NOTICE 8',SYSDATE,'하나','hana',0);
INSERT INTO NOTICEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM NOTICEBOARD),
'NOTICE 9','NOTICE 9',SYSDATE,'하나','hana',0);
INSERT INTO NOTICEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM NOTICEBOARD),
'NOTICE 10','NOTICE 10',SYSDATE,'하나','hana',0);
INSERT INTO NOTICEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM NOTICEBOARD),
'NOTICE 11','NOTICE 11',SYSDATE,'하나','hana',0);
INSERT INTO NOTICEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM NOTICEBOARD),
'NOTICE 12','NOTICE 12',SYSDATE,'하나','hana',0);
INSERT INTO NOTICEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM NOTICEBOARD),
'NOTICE 13','NOTICE 13',SYSDATE,'하나','hana',0);
INSERT INTO NOTICEBOARD (PNUM,PTITLE,PCONTENT,PDATE,MNAME,MID,CNT) VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM NOTICEBOARD),
'NOTICE 14','NOTICE 14',SYSDATE,'하나','hana',0);
